date.timezone = Europe/Riga
default_charset = UTF-8
upload_max_filesize = 5M
post_max_size = 32M
display_errors = Off
log_errors = On
session.cookie_httponly = 0
session.cookie_samesite = Lax

session.name = rootrepair

